In [24]:
import pandas as pd
import gensim
from collections import namedtuple
import numpy as np

In [25]:
recipes_df = pd.read_csv("clean_data.csv")

In [26]:
def clean_list(ingredient_list):
    ingredient_list = ingredient_list[2:-2]
    ingredient_list = ''.join(ingredient_list)
    ingredient_list = ingredient_list.split("', '")
    return ingredient_list

In [27]:
recipes_df["Clean_bag"]=recipes_df["Bag_Of_Ingredients"].map(clean_list)

In [180]:
bag_of_ingredients = recipes_df["Clean_bag"][0:2000]
bag_of_ingredients

0       [chicken, acorn, squash, sage, rosemary, butte...
1       [egg, whites, new, potatoes, ground, black, pe...
2       [evaporated, milk, milk, garlic, powder, onion...
3       [round, italian, loaf, olive, oil, sweet, ital...
4       [dark, brown, bourbon, fresh, lemon, juice, ap...
                              ...                        
1995    [olive, oil, white, onion, garlic, cloves, cor...
1996    [dried, chiles, árbol, seeds, ribs, tomatillos...
1997    [soy, sauce, sesame, oil, red, pepper, garlic,...
1998    [pork, shoulder, boston, butt, white, onion, r...
1999    [allpurpose, flour, stick, butter, granulated,...
Name: Clean_bag, Length: 2000, dtype: object

In [181]:
' '.join(bag_of_ingredients[0])

'chicken acorn squash sage rosemary butter ground allspice red pepper ground black pepper loaf sturdy white bread apples gala pink lady extravirgin olive oil red onion apple cider vinegar white miso allpurpose flour butter dry white wine chicken broth white miso ground pepper'

In [152]:
bag_of_ingredients = [' '.join(i) for i in bag_of_ingredients]

In [182]:
docs = []
analyzedDocument = namedtuple('AnalyzedDocument', 'words tags')
for i, text in enumerate(bag_of_ingredients):
    tags = [i]
    docs.append(analyzedDocument(text, tags))

In [184]:
docs[0]

AnalyzedDocument(words=['chicken', 'acorn', 'squash', 'sage', 'rosemary', 'butter', 'ground', 'allspice', 'red', 'pepper', 'ground', 'black', 'pepper', 'loaf', 'sturdy', 'white', 'bread', 'apples', 'gala', 'pink', 'lady', 'extravirgin', 'olive', 'oil', 'red', 'onion', 'apple', 'cider', 'vinegar', 'white', 'miso', 'allpurpose', 'flour', 'butter', 'dry', 'white', 'wine', 'chicken', 'broth', 'white', 'miso', 'ground', 'pepper'], tags=[0])

In [157]:
model = gensim.models.doc2vec.Doc2Vec(docs,vector_size=50, min_count=5, epochs=50)

In [125]:
model.dv[0]

array([ 0.24197641, -0.02445859, -0.00326098,  0.06139241, -0.07989021,
       -0.22866349, -0.17488764, -0.03433101, -0.1289581 , -0.5137616 ,
       -0.10316258,  0.02797434, -0.24201329,  0.04295552, -0.08299074,
       -0.3438963 , -0.26116714,  0.29388008, -0.07158969, -0.55803204,
       -0.11007298, -0.07274986,  0.4576786 , -0.04881627, -0.33012903,
        0.01321315, -0.5123358 , -0.02412922,  0.10079105,  0.41407886,
        0.37535805, -0.23942783, -0.21409446, -0.16591   ,  0.08921493,
       -0.4045692 , -0.70570284, -0.11214074,  0.08760179,  0.08898778,
        0.11049935,  0.12668572, -0.1438299 ,  0.04167461,  0.3837487 ,
        0.07198523, -0.0196912 ,  0.04038083,  0.4233031 , -0.34273905],
      dtype=float32)

In [126]:
ingredients = ["parmisan","cheese","avocado","bread","mushrooms","beans","sausage"]

In [127]:
av_in_vector = model.infer_vector(ingredients)

In [128]:
from numpy import dot
from numpy.linalg import norm

def similar_recipe(ingredients):
    cos_sim = []
    for i in range(0,len(model.dv)):
            cos_sim.append(np.dot(ingredients,model.dv[i])/(norm(ingredients)*norm(model.dv[i])))
    dis_array = np.array(cos_sim)
    return dis_array

In [129]:
def getListofRecipes(cos_sim,n):
    n_index = (-cos_sim).argsort()[:n]
    titles = []
    for i in n_index:
        titles.append(recipes_df.iloc[i,1:3])
    return titles

In [130]:
pd.DataFrame(getListofRecipes(similar_recipe(av_in_vector),10))

Title  \
679                              Cucumber-Seaweed Salad   
1223  Romano Beans with Mustard Vinaigrette and Walnuts   
168                               Sorrel (Hibiscus) Tea   
656   Grilled Salt-and-Pepper Black Bass with Curry ...   
977                         Warm-Spiced Saucy Lamb Stew   
301                              Pickle Brine Spice Rub   
491                       Lebkuchen (German Honey Bars)   
1536                 Seared Radicchio and Roasted Beets   
1007           Costa Rican Breakfast Bowl (Gallo Pinto)   
178           Cornbread Muffins With Whipped Sweet Corn   

                                            Ingredients  
679   ['3/4 ounce dried wakame seaweed, cut into 1-i...  
1223  ['1 cup walnuts', '3 lb. Romano beans or green...  
168   ['2 cups dried hibiscus (sorrel) flowers', '1⁄...  
656   ['1 cup grapeseed or other neutral oil, divide...  
977   ['1/2 medium head of cauliflower', '3 Tbsp. ex...  
301   ['4 Tbsp. coriander seeds', '6 Tbsp. vinegar p...  
491   ['1 cup (320g) honey', '2 tablespoons (30g) wa...  
1536  ['6 medium beets, scrubbed', '5 tablespoons ex...  
1007  ['1/2 yellow onion, cut into 1/4-inch dice (ab...  
178   ['3 tablespoons coconut oil, plus more for gre...

# Test doc2vec model

In [145]:
import os, sys
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
parent_path = os.path.split(os.getcwd())[0]
if parent_path  not in sys.path:
    sys.path.append(parent_path)

In [10]:
from wots_cookin.data import load_data, load_full_stopwords, remove_formatting, load_clean_data, doc2vec_preprocessing
from wots_cookin.doc2vec_trainer import *

In [11]:
df = load_clean_data()

8 rows containing NAs dropped...
6 rows containing empty ingredients dropped...
Data loaded.
Cleaning formatting...
Returning list of 461 stopwords
Removing stopwords...
Order's up!
Returning dataframe with Bag_Of_Ingredients


In [12]:
df.head()

Title  \
0  Miso-Butter Roast Chicken With Acorn Squash Pa...   
1                    Crispy Salt and Pepper Potatoes   
2                        Thanksgiving Mac and Cheese   
3                 Italian Sausage and Bread Stuffing   
4                                       Newton's Law   

                                         Ingredients  \
0  ['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...   
1  ['2 large egg whites', '1 pound new potatoes (...   
2  ['1 cup evaporated milk', '1 cup whole milk', ...   
3  ['1 (¾- to 1-pound) round Italian loaf, cut in...   
4  ['1 teaspoon dark brown sugar', '1 teaspoon ho...   

                                        Instructions  \
0  Pat chicken dry with paper towels, season all ...   
1  Preheat oven to 400°F and line a rimmed baking...   
2  Place a rack in middle of oven; preheat to 400...   
3  Preheat oven to 350°F with rack in middle. Gen...   
4  Stir together brown sugar and hot water in a c...   

                                          Image_Name  \
0  miso-butter-roast-chicken-acorn-squash-panzanella   
1         crispy-salt-and-pepper-potatoes-dan-kluger   
2         thanksgiving-mac-and-cheese-erick-williams   
3          italian-sausage-and-bread-stuffing-240559   
4                 newtons-law-apple-bourbon-cocktail   

                                 Cleaned_Ingredients  \
0  ['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...   
1  ['2 large egg whites', '1 pound new potatoes (...   
2  ['1 cup evaporated milk', '1 cup whole milk', ...   
3  ['1 (¾- to 1-pound) round Italian loaf, cut in...   
4  ['1 teaspoon dark brown sugar', '1 teaspoon ho...   

                                  Bag_Of_Ingredients  
0  [chicken, acorn, squash, sage, rosemary, butte...  
1  [egg, whites, new, potatoes, ground, black, pe...  
2  [evaporated, milk, milk, garlic, powder, onion...  
3  [round, italian, loaf, olive, oil, sweet, ital...  
4  [dark, brown, bourbon, fresh, lemon, juice, ap...

In [189]:
bag_of_ingredients = df['Bag_Of_Ingredients'][0:2000]

In [170]:
model = Doc2VecTrainer()

In [190]:
bag_of_ingredients = doc2vec_preprocessing(bag_of_ingredients)

In [191]:
bag_of_ingredients[0]

AnalyzedDocument(words=['chicken', 'acorn', 'squash', 'sage', 'rosemary', 'butter', 'ground', 'allspice', 'red', 'pepper', 'ground', 'black', 'pepper', 'loaf', 'sturdy', 'white', 'bread', 'apples', 'gala', 'pink', 'lady', 'extravirgin', 'olive', 'oil', 'red', 'onion', 'apple', 'cider', 'vinegar', 'white', 'miso', 'allpurpose', 'flour', 'butter', 'dry', 'white', 'wine', 'chicken', 'broth', 'white', 'miso', 'ground', 'pepper'], tags=[0])

In [192]:
model.train_model(bag_of_ingredients)

Recipes corpus set
Model trained!


In [193]:
model.model.dv

In [194]:
ingredients =[ 'chicken', 'acorn', 'squash', 'sage', 'rosemary', 'butter', 'ground', 'allspice', 'red', 'pepper', 'ground', 'black', 'pepper', 'loaf', 'sturdy', 'white', 'bread', 'apples', 'gala', 'pink', 'lady', 'extravirgin', 'olive', 'oil', 'red', 'onion', 'apple', 'cider', 'vinegar', 'white', 'miso', 'allpurpose', 'flour', 'butter', 'dry', 'white', 'wine', 'chicken', 'broth', 'white', 'miso', 'ground', 'pepper']

In [195]:
model.get_ingredients_vector(ingredients)

array([-0.00475507,  0.11997607, -0.09517194,  0.02346379,  0.03063754,
       -0.01324059,  0.01678705, -0.06888784, -0.06190748,  0.01709206,
        0.05240265,  0.04429502, -0.11902413, -0.0778882 , -0.07986069,
        0.17412157, -0.02143359,  0.05140143, -0.05761551, -0.07579109,
       -0.08365007,  0.03830429, -0.09540305, -0.15589367, -0.086905  ,
       -0.00526428,  0.18678032, -0.11180825,  0.09969003, -0.11832611,
       -0.06010412, -0.04320149,  0.07060476,  0.13128188, -0.02126477,
       -0.05280431,  0.03399032,  0.04824045,  0.05225614, -0.07418419,
       -0.03391881,  0.01117652, -0.00925263,  0.05628886, -0.03894513,
       -0.02443234,  0.05185473,  0.096393  , -0.05823968,  0.12364227],
      dtype=float32)

In [196]:
model.get_similarity_score(ingredients)

array([ 0.6970462 ,  0.14644414,  0.06359537, ...,  0.33516115,
       -0.05154458,  0.16619058], dtype=float32)

In [197]:
model.get_similar_recipes(ingredients,df,nrow=30)

Title  \
0     Miso-Butter Roast Chicken With Acorn Squash Pa...   
1595                          Stock-Braised Turkey Legs   
1234                                      Ramp Fritters   
137                                   Jerk Potato Salad   
171                              Pulled Pork Sandwiches   
872                            Pimiento Cheese Crackers   
1586                                   Make-Ahead Gravy   
1603  Green Bean and Mushroom Casserole with Crispy ...   
1710                       Grilled Turkey Under a Brick   
1826                            Cinnamon Apple Cupcakes   
1669  Vegan "Tofurkey" with Mushroom Stuffing and Gravy   
735                                      Cashew Chicken   
1738                  Tomato Tart with Chickpea Crumble   
1451                          Cashew and Coconut Shrimp   
1602       Caramel Apple Drip Cake with Candied Walnuts   
1599          Spiced Turkey Chili with Spaghetti Squash   
1247                 Pan-Seared Ribeye with Miso Butter   
945        Skillet Dressing with Cornbread and Biscuits   
122               Tortillas de Harina (Flour Tortillas)   
1246              Blackened Salmon with Pineapple Salsa   
59                                 Salt-and-Pepper Fish   
963                                   Turkey for Twenty   
309                                  Cabbage Potato Pie   
1397                 Sticky Maple and Bourbon Pork Ribs   
1953                               Korean Fried Chicken   
1169                               Sweet-and-Spicy Slaw   
780   Corned Beef with Crispy Roasted Potatoes and C...   
204                         Pork and Asparagus Stir-Fry   
159   Caribbean Smothered Chicken With Coconut, Lime...   
600                                      Tomato Galette   

                                            Ingredients  \
0     ['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...   
1595  ['2 tablespoons Diamond Crystal or 1 tablespoo...   
1234  ['1 cup all-purpose flour', '3/4 cup rice flou...   
137   ['Zest and juice of 2 limes', '2 habanero chil...   
171   ['4 tablespoons sweet paprika', '2 tablespoons...   
872   ['12 oz. sharp cheddar, coarsely grated (about...   
1586  ['1 tablespoon vegetable oil', '1 pound chicke...   
1603  ['2 pounds mixed wild mushrooms, trimmed, halv...   
1710  ['Diamond Crystal or Morton kosher salt (see b...   
1826  ['1 cup granulated sugar', '3/4 cup butter, so...   
1669  ['4 tablespoons vegetable oil, divided, plus m...   
735   ['2 Tbsp. oyster sauce', '1 Tbsp. rice vinegar...   
1738  ['1 (7 1/2-ounce) prepared pie crust or homema...   
1451  ['1/2 cup mango peach jam', '2 tablespoons whi...   
1602  ['1 cup raw walnuts', 'Nonstick vegetable oil ...   
1599  ['2 small or 1 large spaghetti squash (3–3 1/2...   
1247  ['1/4 cup (56 g) unsalted butter, softened', '...   
945   ['1 1/2 cups fine-grind white cornmeal', '1/2 ...   
122   ['3 cups all-purpose flour, plus more if neede...   
1246  ['1 tablespoon ground paprika', '1 teaspoon ga...   
59    ['1 cup short-grain sushi rice', '8 scallions'...   
963   ['3/4 cup Diamond Crystal or 7 Tbsp. Morton ko...   
309   ['2 lb. russet potatoes, peeled, cut into 2" p...   
1397  ['2 cups (500ml) malt vinegar', '2 quarts (2 l...   
1953  ['Vegetable or canola oil (for frying; about 2...   
1169  ['1/2 cup apple cider vinegar', '6 Tbsp. peach...   
780   ['1 (3–4-lb.) corned beef brisket', '2 lb. rus...   
204   ['3 tsp. peanut or vegetable oil, divided', '2...   
159   ['1 teaspoon vegetable oil', '4 large bone-in,...   
600   ['2 cups all-purpose flour, plus more for dust...   

                                           Instructions  \
0     Pat chicken dry with paper towels, season all ...   
1595  Place salt and brown sugar in a small bowl and...   
1234  Remove any slippery outer layers from ramp bul...   
137   Using a fork, mix lime zest and juice, chiles,...   
171   Add paprika, chili powder, cumin, brown sugar,...   
872   Pulse cheese, flour, salt, and